<?php
/**
 * SystemRoleEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  BlackboardRest
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Learn APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3200.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BlackboardRest\Model;

use \ArrayAccess;

/**
 * SystemRoleEnum Class Doc Comment
 *
 * @category    Class
 * @package     BlackboardRest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SystemRoleEnum {
    const SYSTEM_ADMIN = 'SystemAdmin';
    const SYSTEM_SUPPORT = 'SystemSupport';
    const COURSE_CREATOR = 'CourseCreator';
    const COURSE_SUPPORT = 'CourseSupport';
    const ACCOUNT_ADMIN = 'AccountAdmin';
    const GUEST = 'Guest';
    const USER = 'User';
    const OBSERVER = 'Observer';
    const INTEGRATION = 'Integration';
    const PORTAL = 'Portal';
    

    
}

