<?php
/**
 * Input3Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  BlackboardRest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Learn APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3200.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BlackboardRest;

/**
 * Input3Test Class Doc Comment
 *
 * @category    Class */
// * @description Input3
/**
 * @package     BlackboardRest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Input3Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Input3"
     */
    public function testInput3()
    {

    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {

    }

    /**
     * Test attribute "data_source_id"
     */
    public function testPropertyDataSourceId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "ultra_status"
     */
    public function testPropertyUltraStatus()
    {

    }

    /**
     * Test attribute "allow_guests"
     */
    public function testPropertyAllowGuests()
    {

    }

    /**
     * Test attribute "read_only"
     */
    public function testPropertyReadOnly()
    {

    }

    /**
     * Test attribute "term_id"
     */
    public function testPropertyTermId()
    {

    }

    /**
     * Test attribute "availability"
     */
    public function testPropertyAvailability()
    {

    }

    /**
     * Test attribute "enrollment"
     */
    public function testPropertyEnrollment()
    {

    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {

    }

}
