<?php
/**
 * OAuth2AccessTokenTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BlackboardRest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Learn APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3200.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BlackboardRest;

/**
 * OAuth2AccessTokenTest Class Doc Comment
 *
 * @category    Class */
// * @description OAuth2AccessToken
/**
 * @package     BlackboardRest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OAuth2AccessTokenTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "OAuth2AccessToken"
     */
    public function testOAuth2AccessToken()
    {

    }

    /**
     * Test attribute "access_token"
     */
    public function testPropertyAccessToken()
    {

    }

    /**
     * Test attribute "token_type"
     */
    public function testPropertyTokenType()
    {

    }

    /**
     * Test attribute "expires_in"
     */
    public function testPropertyExpiresIn()
    {

    }

}
