<?php
/**
 * CoursesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BlackboardRest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Learn APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3200.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BlackboardRest;

use \BlackboardRest\Configuration;
use \BlackboardRest\ApiClient;
use \BlackboardRest\ApiException;
use \BlackboardRest\ObjectSerializer;

/**
 * CoursesApiTest Class Doc Comment
 *
 * @category Class
 * @package  BlackboardRest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CoursesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for coursesCourseIdChildrenChildCourseIdGet
     *
     * Get Child.
     *
     */
    public function testCoursesCourseIdChildrenChildCourseIdGet()
    {

    }

    /**
     * Test case for coursesCourseIdChildrenGet
     *
     * Get Children.
     *
     */
    public function testCoursesCourseIdChildrenGet()
    {

    }

    /**
     * Test case for coursesCourseIdDelete
     *
     * Delete Course.
     *
     */
    public function testCoursesCourseIdDelete()
    {

    }

    /**
     * Test case for coursesCourseIdGet
     *
     * Get Course.
     *
     */
    public function testCoursesCourseIdGet()
    {

    }

    /**
     * Test case for coursesCourseIdPatch
     *
     * Update Course.
     *
     */
    public function testCoursesCourseIdPatch()
    {

    }

    /**
     * Test case for coursesGet
     *
     * Get Courses.
     *
     */
    public function testCoursesGet()
    {

    }

    /**
     * Test case for coursesPost
     *
     * Create Course.
     *
     */
    public function testCoursesPost()
    {

    }

}
