<?php
/**
 * DataSourcesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BlackboardRest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Learn APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3200.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BlackboardRest;

use \BlackboardRest\Configuration;
use \BlackboardRest\ApiClient;
use \BlackboardRest\ApiException;
use \BlackboardRest\ObjectSerializer;

/**
 * DataSourcesApiTest Class Doc Comment
 *
 * @category Class
 * @package  BlackboardRest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DataSourcesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for dataSourcesDataSourceIdDelete
     *
     * Delete Data Source.
     *
     */
    public function testDataSourcesDataSourceIdDelete()
    {

    }

    /**
     * Test case for dataSourcesDataSourceIdGet
     *
     * Get Data Source.
     *
     */
    public function testDataSourcesDataSourceIdGet()
    {

    }

    /**
     * Test case for dataSourcesDataSourceIdPatch
     *
     * Update Data Source.
     *
     */
    public function testDataSourcesDataSourceIdPatch()
    {

    }

    /**
     * Test case for dataSourcesGet
     *
     * Get Data Sources.
     *
     */
    public function testDataSourcesGet()
    {

    }

    /**
     * Test case for dataSourcesPost
     *
     * Create Data Source.
     *
     */
    public function testDataSourcesPost()
    {

    }

}
